### ISSUE TITLE
Error while generating the documentation

### ISSUE THREAD

**Issue by mriedmueller** [msornakumar/BISM-SSAS-Tabular-Documentation-Tool#3]
After chosing a cube and clicking on "Generate Document" I receive an error:

Getting Metadata for CPM_OLAP_NEU - MSBI CPM Addison Started 
Getting Metadata for CPM_OLAP_NEU - MSBI CPM Addison Connections Started 
Getting Metadata for CPM_OLAP_NEU - MSBI CPM Addison Connections Completed 
Getting Metadata for CPM_OLAP_NEU - MSBI CPM Addison Dimensions Started 
--------------------------------------------------------------------------------------
Error Occured
--------------------------------------------------------------------------------------
System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
   bei BISMDocumentor_DescriptionEditor.frmBISMDocumentor.WriteDimension()
   bei BISMDocumentor_DescriptionEditor.frmBISMDocumentor.cmdGenerateDocument_Click(Object sender, EventArgs e)

The resulting Excel-file is partially filled, so the generation did at least start correctly.

Regards,
Michael

**Comment by msornakumar** [comment]
Hi Michael ,
  Thanks for your feedback. Have uploaded a latest version of the code which will generate the file in the given folder and no need for the template as well. Please try running this version and provide your feedback.

Thanks

Sorna
