### ISSUE TITLE
Compatibly level SQL Server 2016 RTM (1200) does not have CUBEs

### ISSUE THREAD

**Issue by gordynorth** [msornakumar/BISM-SSAS-Tabular-Documentation-Tool#6]
Cannot run the tool against newer tabular models as they do not have any CUBEs. 
The SQL Server version I am using is SQL Server 2016 RTM (1200). The models loaded with this compatibility level do not have any CUBEs and the tool fails. 

I ran a DSV query against the database and verified that there are no CUBEs:
SELECT [CATALOG_NAME] AS [DATABASE],CUBE_CAPTION AS [CUBE/PERSPECTIVE],BASE_CUBE_NAME
FROM $system.MDSchema_Cubes

Thank you

**Comment by msornakumar** [comment]
Thanks for the feedback.

Looking into this issue. Will update ASAP.

**Comment by msornakumar** [comment]
Hi gordynorth ,

  Have fixed the code to work for 2016 and 2017 as well. Please try the latest release and let me know incase of any issues. Thank you very much for your feedback.

Warm Regards,

Sorna

**Comment by gordynorth** [comment]
Works like a charm. Thank you so much for fixing this.
